# Generated by Django 5.1.1 on 2024-09-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_table',
            name='age',
            field=models.DateField(),
        ),
    ]
