from django.urls import path

from myapp import views

urlpatterns = [
    path('',views.login,name="login"),
    path('login_post',views.login_post,name="login_post"),
    path('ForgotPassword',views.ForgotPassword,name="ForgotPassword"),
    path('adddep',views.adddep,name="adddep"),
    path('addep_post',views.addep_post,name="addep_post"),
    path('adminhome',views.adminhome,name="adminhome"),
    path('changepassword',views.changepassword,name="changepassword"),
    path('complaint_sendreply/<int:id>',views.complaint_sendreply,name="complaint_sendreply"),
    path('acceptbooking/<int:id>',views.acceptbooking,name="acceptbooking"),
    path('rejectbooking/<int:id>',views.rejectbooking,name="rejectbooking"),
    path('senreply',views.senreply,name="senreply"),
    path('ForgotPassword',views.ForgotPassword,name="ForgotPassword"),
    path('login',views.login,name="login"),
    path('ManageDepartment',views.ManageDepartment,name="ManageDepartment"),
    path('verifyhospital',views.verifyhospital,name="verifyhospital"),
    path('admin_view_accepted_hospital',views.admin_view_accepted_hospital,name="admin_view_accepted_hospital"),
    path('accept_hosp/<id>',views.accept_hosp,name="accept_hosp"),
    path('reject_hosp/<id>',views.reject_hosp,name="reject_hosp"),
    path('viewcomplaints',views.viewcomplaints,name="viewcomplaints"),
    path('viewcomplaints_search',views.viewcomplaints_search,name="viewcomplaints_search"),
    path('viewcomplaints/<hocid>', views.viewcomplaints, name="viewcomplaints"),
    path('reject_hosp/<id>', views.reject_hosp, name="reject_hosp"),
    path('ManageDepartment_search', views.ManageDepartment_search, name="ManageDepartment_search"),

    path('viewdoctor/<hosid>',views.viewdoctor,name="viewdoctor"),
    path('admin_search_doctor',views.admin_search_doctor,name="admin_search_doctor"),
    path('viewpatient',views.viewpatient,name="viewpatient"),
    path('changepassword_post',views.changepassword_post,name="changepassword_post"),
    # path('admin_view_accepted_hospital',views.admin_view_accepted_hospital,name="admin_view_accepted_hospital"),
    path('viewdoctor/<hosid>', views.viewdoctor, name="viewdoctor"),

    path('verifyhospitalsearch',views.verifyhospitalsearch,name="verifyhospitalsearch"),
    path('viewpatient_serach',views.viewpatient_serach,name="viewpatient_serach"),
    path('ForgotPassword_post',views.ForgotPassword_post,name="ForgotPassword_post"),
    #"+=================hospital======================================="


    path('HOS_Change_password',views.HOS_Change_password,name="HOS_Change_password"),
    path('changepassword_postHOS',views.changepassword_postHOS,name="changepassword_postHOS"),
    path('hospitalhome',views.hospitalhome,name="hospitalhome"),
    path('Hospitalregister',views.Hospitalregister,name="Hospitalregister"),
    path('hospitalregistration_post',views.hospitalregistration_post,name="hospitalregistration_post"),
    path('ManageDoctor',views.ManageDoctor,name="ManageDoctor"),
    path('ManageDoctor_search',views.ManageDoctor_search,name="ManageDoctor_search"),
    path('ManageDoctor_AddNew',views.ManageDoctor_AddNew,name="ManageDoctor_AddNew"),
    path('ManageDoctor_AddNew_post',views.ManageDoctor_AddNew_post,name="ManageDoctor_AddNew_post"),
    path('hospital_delete_doctor/<lid>',views.hospital_delete_doctor,name="hospital_delete_doctor"),
    path('hospital_edit_doctor/<id>',views.hospital_edit_doctor,name="hospital_delete_doctor"),
    path('ManageSchedule/<id>',views.ManageSchedule,name="ManageSchedule"),
    path('ManageSchedule_AddNew_POST',views.ManageSchedule_AddNew_POST,name="ManageSchedule_AddNew_POST"),
    path('deletedepartment/<id>',views.deletedepartment,name="deletedepartment"),
    path('ManageSchedule_AddNew',views.ManageSchedule_AddNew,name="ManageSchedule_AddNew"),
    path('hos_delete_schedules/<schid>',views.hos_delete_schedules,name="hos_delete_schedules"),
    path('ViewBooking',views.ViewBooking,name="ViewBooking"),
    path('ViewBooking_search',views.ViewBooking_search,name="ViewBooking_search"),
    path('ViewBooking_Schedule', views.ViewBooking_Schedule, name="ViewBooking_Schedule"),
    path('ViewProfile', views.ViewProfile, name="ViewProfile"),
    path('update_hosp_profile', views.update_hosp_profile, name="update_hosp_profile"),
#"+=================doctor======================================="



    path('DoctorHome', views.DoctorHome, name="DoctorHome"),
    path('changepasswordDOC', views.changepasswordDOC, name="changepasswordDOC"),
    path('changepassword_postDOC', views.changepassword_postDOC, name="changepassword_postDOC"),
    path('admin_view_accepted_hospital_search', views.admin_view_accepted_hospital_search, name="admin_view_accepted_hospital_search"),

    path('ManageBooking', views.ManageBooking, name="ManageBooking"),
    path('ViewBooking1', views.ViewBooking1, name="ViewBooking1"),
    path('viewratingsearch', views.viewratingsearch, name="viewratingsearch"),
    path('ViewBooking1_Prescription', views.ViewBooking1_Prescription, name="ViewBooking1_Prescription"),
    path('ViewBooking1_Prescription_AddNew', views.ViewBooking1_Prescription_AddNew, name="ViewBooking1_Prescription_AddNew"),
    path('ViewBookingHistory', views.ViewBookingHistory, name="ViewBookingHistory"),
    path('viewrating', views.viewrating, name="viewrating"),
    path('searchViewBookingHistory', views.searchViewBookingHistory, name="searchViewBookingHistory"),
    path('ViewSchedule', views.ViewSchedule, name="ViewSchedule"),
    path('accept_booking/<int:id>', views.accept_booking, name="accept_booking"),
    path('reject_booking/<int:id>', views.reject_booking, name="reject_booking"),
    path('ViewBooking1_Prescription/<int:id>', views.ViewBooking1_Prescription, name="ViewBooking1_Prescription"),
    path('deleteprescription/<int:id>', views.deleteprescription, name="deleteprescription"),

    path('ViewBooking1_Prescription_AddNew_post',views.ViewBooking1_Prescription_AddNew_post, name="ViewBooking1_Prescription_AddNew_post"),
    path('Bookappointment',views.Bookappointment, name="Bookappointment"),
    path('ViewBooking1_Prescription_AddNew_post',views.ViewBooking1_Prescription_AddNew_post, name="ViewBooking1_Prescription_AddNew_post"),
    path('ViewBooking1search',views.ViewBooking1search, name="ViewBooking1search"),
    path('viewdocprofile',views.viewdocprofile, name="viewdocprofile"),
    path('searchManageBooking',views.searchManageBooking, name="searchManageBooking"),
    path('viewdocprofileupdate',views.viewdocprofileupdate, name="viewdocprofileupdate"),
    path('updatedoctorprofile',views.updatedoctorprofile, name="updatedoctorprofile"),
    path('user_reg',views.user_reg, name="user_reg"),
    path('userregistration',views.userregistration, name="userregistration"),

    path('userhome',views.userhome, name="userhome"),
    path('user_view_hospital',views.user_view_hospital, name="user_view_hospital"),
    path('user_updateprofile_post',views.user_updateprofile_post, name="user_updateprofile_post"),
    path('viewdocprofilecode',views.viewdocprofilecode, name="viewdocprofilecode"),
    path('user_view_hospital_serach',views.user_view_hospital_serach, name="user_view_hospital_serach"),
    path('user_view_doctor/<hid>',views.user_view_doctor, name="user_view_hospital_serach"),
    path('User_Scheduleform/<did>',views.User_Scheduleform, name="User_Scheduleform"),
    path('user_book_doctor/<schid>',views.user_book_doctor, name="user_view_hospital_serach"),
    path('Complaints',views.Complaints, name="Complaints"),
    path('Send_Complaint', views.Send_Complaint, name="Send_Complaint"),
    path('Send_Complaint_post', views.Send_Complaint_post, name="Send_Complaint_post"),
    path('Complaints_delete/<cid>', views.Complaints_delete, name="Complaints_delete"),
    path('user_view_doctor_review/<rid>', views.user_view_doctor_review, name="Complaints_delete"),
    path('viewprofileuser', views.viewprofileuser, name="viewprofileuser"),
    path('view_prescription_user/<id>', views.view_prescription_user, name="viewprofileuser"),

]